name: Generate GitHub Trophy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-trophy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: Dasith-Randula
          output_path: trophy.svg
          theme: darkhub
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push trophy.svg
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update GitHub trophy"
          file_pattern: "trophy.svg"
